query stats($owner: String!, $name: String! $first: Int) {
  repository(owner: $owner, name: $name) {
    stargazerCount
    name
    issues(first: $first, states: OPEN, orderBy: {field: CREATED_AT, direction: DESC}) {
      totalCount
    }
    defaultBranchRef {
      target {
        ... on Commit {
          message
          committedDate
          history(first: 1) {
            totalCount
          }
        }
      }
    }
  }
}