/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/trigger/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Bot & API Restart
         * @description Executes update script, closes database connection, and restarts PM2 processes.
         */
        post: operations["postApiV1TriggerRestart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trigger/wipe-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wipe Audit Logs
         * @description Truncates the logs.json file.
         */
        post: operations["postApiV1TriggerWipe-logs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trigger/create-announcement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Announcement */
        post: operations["postApiV1TriggerCreate-announcement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Logs
         * @description Retrieves Winston log entries typed by LogLevel and LogMeta variants.
         */
        get: operations["getApiV1InfoLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Announcements */
        get: operations["getApiV1InfoAnnouncements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bot Metrics */
        get: operations["getApiV1InfoStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/rsa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public RSA Key
         * @description Retrieves the public RSA key used for client-side token encryption.
         */
        get: operations["getApiV1PublicRsa"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register AniList Account
         * @description Decrypts the provided AniList token, checks registration status, and creates a user entry linked to the discord user ID.
         */
        post: operations["postApiV1PublicRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postApiV1TriggerRestart: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 202 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "postApiV1TriggerWipe-logs": {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "postApiV1TriggerCreate-announcement": {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    announcement: string;
                    date: string;
                };
                "application/x-www-form-urlencoded": {
                    announcement: string;
                    date: string;
                };
                "multipart/form-data": {
                    announcement: string;
                    date: string;
                };
            };
        };
        responses: {
            /** @description Response for status 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getApiV1InfoLogs: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description ISO Timestamp generated by Winston */
                        timestamp?: string;
                        /** @enum {string} */
                        level: "error" | "warn" | "info" | "http" | "verbose" | "debug" | "silly";
                        message: string;
                        meta?: ({
                            /**
                             * Generic Type
                             * @constant
                             */
                            type: "generic";
                            command?: string;
                            subcommand?: string;
                            user?: string;
                            userId?: string;
                            guildId?: string;
                        } & {
                            [key: string]: unknown;
                        }) | {
                            /**
                             * Command Type
                             * @constant
                             */
                            type: "command";
                            command: string;
                            subcommand?: string;
                            user: string;
                            userId: string;
                            guildId: ((string | null) | null) | null;
                        } | ({
                            /**
                             * Command Debug Type
                             * @constant
                             */
                            type: "commandDebug";
                            command: string;
                            subcommand?: string;
                        } & {
                            [key: string]: unknown;
                        }) | {
                            /**
                             * Event Type
                             * @constant
                             */
                            type: "event";
                            name: string;
                            isOnce: boolean;
                        } | {
                            /**
                             * GraphQL Type
                             * @constant
                             */
                            type: "graphql";
                            query: string;
                            vars: {
                                [key: string]: unknown;
                            };
                            durationMs?: number;
                            rateLimitRemaining?: number;
                            authenticated: boolean;
                        } | {
                            /**
                             * Check Type
                             * @constant
                             */
                            type: "check";
                            name?: string;
                            optional?: boolean;
                            purpose?: string;
                            why?: unknown;
                            total?: number;
                        } | {
                            /**
                             * Startup Type
                             * @constant
                             */
                            type: "startup";
                            environment?: string;
                            user?: string;
                            total?: number;
                            commands?: string[];
                            error?: string;
                            component?: string;
                        } | ({
                            /**
                             * Error Type
                             * @constant
                             */
                            type: "error";
                            errorName?: string;
                            stack?: string;
                            errors?: string[];
                        } & {
                            [key: string]: unknown;
                        });
                    }[];
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getApiV1InfoAnnouncements: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        announcement: string;
                        date: string;
                    }[];
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getApiV1InfoStats: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        servers: number;
                        members: number;
                        registered: number;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    getApiV1PublicRsa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PEM-encoded public key string */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    postApiV1PublicRegister: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description RSA-encrypted AniList JWT */
                    token: string;
                };
                "application/x-www-form-urlencoded": {
                    /** @description RSA-encrypted AniList JWT */
                    token: string;
                };
                "multipart/form-data": {
                    /** @description RSA-encrypted AniList JWT */
                    token: string;
                };
            };
        };
        responses: {
            /** @description Response for status 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
}
